[package]
name = "lyon1_cas_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", default-features = false, features = ["cookies", "blocking", "http2", "charset", "rustls-tls"] }
soup = "0.5.1"

[dev-dependencies]
dotenvy = "0.15.7"